name: CICDlab

on: [push]
jobs:

  CICDlab-try-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
          with:
            python-version: "3.10"
            cache: "pip"
        uses: actions/setup-python@v4
        with:
          python-version: $ {{matrix.python-version }}
      - name: Build package
        run: python -m build
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Test with unittests
        run:
          python -m tests
      
